### ISSUE TITLE
Idea and features

### ISSUE THREAD

**Issue by jessieAnhNguyen** [MLH-Fellowship/0.4.1-Quarantime#1]
## Idea
We're going to implement a social media website/ app for people to share their open source projects, or any other activities they are doing during this quarantine time.
## Features
We'll implement these features for our app:
1. Log-in to personal account:
- Users log in with their email address and password to their account using **Firebase**

2. Newsfeed page: where people post/ share what they are working on
- For open source projects, can design a template for people to use (e.g: technologies they use, any help they need, etc.) using **React JSON Schema**
- Besides open source, people can post pictures and share about other non-tech activities. For eg: "I'm practicing LeetCode and need someone to share the Premium account with."

3. Tag system and Trending summary:
- Each post can include tags to determine which category it falls into.
- Depending on the tags, can create a nice summary of data using "React JSON Schema"

4. Chat feature:
- A basic messaging function for users to connect with each other
- Implement using **React**

**Comment by saphal1998** [comment]
To implement login, I guess we can use Firebase, relatively easy to setup. And let's design the template using react-json-schema?

**Comment by jessieAnhNguyen** [comment]
June 3 - To-dos:
1. Saphal: 
- Implement the form to take data for students
- Create a newsfeed

2. Kunal:
- Implement the authentication
- Backend: connect with server

3. Aniketh:
- Build/ design the front-end
- Finish up on the Log-In using Firebase 

4. Jessie:
- Implement the chat function using socket.io

**Comment by kunal-kushwaha** [comment]
Similar to #16. Closing this for now.
