### ISSUE TITLE
Demo outline and timeline

### ISSUE THREAD

**Issue by jessieAnhNguyen** [MLH-Fellowship/0.4.1-Quarantime#16]
## Information:
- [x] 1. Project Name & Purpose: @jessieAnhNguyen 
- Name: Quarantime
- Purpose: In this quarantine time, millions of people all over the world are in lockdown and staying in their homes. A lot of them are working on awesome open-source projects, but might not have a way to share their progress or receive help from others. Thus, "Quarantime" is a social media platform for people to share their projects, connect with other developers, and make opportunities available to the community. 

- [x] 2. Introduce the Team:
- Kunal: Sophore (becoming Junior) studying Computer Science and Engineering in India. Open Source enthusiast, community guy ☀️
- Aniketh: Final year undergraduate student studying  Computer Science Engineering at Karunya University
- Saphal: Final year undergraduate student studying Electronics and Communication Engineering at Delhi Technological University
- Jessie: junior studying CS at University of Rochester, currently in Vietnam 

- [x] 3. Explain the problem: @jessieAnhNguyen 
    - This Pandemic has affected a lot of people, especially students. We believe in the power of the community.
    - We have focussed on 2 aspects here for students: 
        1. Lack of awareness regarding opportunities
        2. Finding it difficult to get started with Open Source
    - We understand that it gets overwhelming to get started with open source for a beginner. Most of the students don't get the right guidance during their school/college years. They are unaware of the opportunities available.
- Students don't have yet a fun social media platform where they can post about what they are working on and share opportunities before and after the lockdown.
- Also don't have a way to find what's trending in the open-source community (technologies, platforms, etc.)
- Students might also wanna have a group chat to discuss with each other about a project, etc. 

- [x] 4. Demo the Solution: @anikethsaha @jessieAnhNguyen @kunal-kushwaha 
Keeping that in mind, we have built this social media platform for people to:
    - Share their stories during Quarantine time, helping the community by making them aware of the opportunities available (both during and after lockdown) that they might not be aware of.
    - Open-source the projects that they have worked on, be it at Hackathons, School projects, etc. so that other students can collaborate & learn in addition to helping the project grow. This will increase community engagement among students and promote the open source culture.

- [x] 5. Open Source Project Tie-in: @kunal-kushwaha 
- Technologies we used: 
    - React
    - Semantic UI React
    - GraphQL
    - MongoDB Atlas
    - Node.js
    - Express.js
    - mongoose
    - react-router-dom
    - Apollo Server
    - JWT (JSONWebToken)
    - bcrypt.js
    - Sockets
    - Markdown
    - GitHub for collaboration: issues, pull requests

- [x] 6. Individual contributions:

- Kunal: 
    - Backend including Auth, DBMS (MongoDb Atlas)
    - Integrating Frontend with Backend using Apollo
    - state management using apollo-cache
    - Frontend (basic design using React)
    - Deployed backend on Heroku & Client on Netlify - Integrated both using proxy
    - Created Documentations
- Aniketh: 
    - Created the Project Architecture
    - Created the frontend and react components
    - Graphql and mongodb Schema Design
    - Client and server integrations 
    - Extensive code review
- Jessie:
    - Frontend (enhancing UI design using React)
    - Created working chat feature to be implemented in next release
    - Created backend for chat feature using sockets
    - Created frontend components
    - Created Documentations
    - Managing issues and tasks on GitHub
- Saphal:
    - Designed React components
    - Participated in brainstorming discussions & gave valuable inputs for designing backend
    - Provided solutions to various blockers 

- [x] 7. Where to find it: 
- URL for GitHub: [Quarantime](https://github.com/MLH-Fellowship/0.4.1-Quarantime)

**Comment by jessieAnhNguyen** [comment]
@kunal-kushwaha  @saphal1998  @anikethsaha please have a look and fill out the parts that concern your personal info & your contributions. Also feel free to add anything that I'm missing

**Comment by kunal-kushwaha** [comment]
Updated 👍
